### ISSUE TITLE
Investigate and fix "Home" link

### ISSUE THREAD

**Issue by codeTrackLift** [mitxpro-dev/learnjs#10]
- Clicking on the "Home" link takes you to `https://mitxpro-dev.github.io/lea`, which results in a 404
- The "About" and "Challenges" links work as expected
- Investigate why this is happening and propose a solution

**Comment by HudsonGraeme** [comment]
Did some investigation here and the cause isn't immediately obvious.. Everything looks like it's in order. I'll circle back tonight and attempt a PR

**Comment by codeTrackLift** [comment]
@HudsonGraeme saved the day! 🔥
