### ISSUE TITLE
Create homepage hero section

### ISSUE THREAD

**Issue by HudsonGraeme** [mitxpro-dev/learnjs#12]
### Create a `Hero` section for the homepage

Currently the homepage displays a centered piece of text

<img width="1001" alt="image" src="https://github.com/mitxpro-dev/learnjs/assets/25019680/590a2430-461e-480b-b64c-7049053876ea">

We need a proper [`Hero`](https://uxplanet.org/website-hero-section-6-design-best-practices-6fe14447753?gi=2d9d97d85e0c) section at the top of the site that captivates new site visitors and prompts them to explore further.

### Requirements

- A new hero section is created and replaces the existing centered Learn JS text on the page
- A cool image relating to learning / js / code is displayed in the hero along with heading and body text explaining simply what the site is and what it offers users
- One or two call to action buttons are beneath the hero / text allowing users to navigate to the challenges or about pages directly

Reference hero sections
- [Design reference](https://uxplanet.org/website-hero-section-6-design-best-practices-6fe14447753?gi=2d9d97d85e0c)
- [ThreeJS-Journey Hero](https://threejs-journey.com)
- [NextJS Hero](https://nextjs.org/)
- [Chakra UI Hero](https://chakra-ui.com/)
- [Dribbble Hero Sections](https://dribbble.com/tags/hero_section)

**Comment by HudsonGraeme** [comment]
Improvements / suggestions / changes welcomed @codeTrackLift!

**Comment by codeTrackLift** [comment]
This is being address in [PR# 13](https://github.com/mitxpro-dev/learnjs/pull/13)
