### ISSUE TITLE
Proposal: Site foundations

### ISSUE THREAD

**Issue by HudsonGraeme** [mitxpro-dev/learnjs#2]
### Description

This proposal outlays the general design of the application in terms of tech stack.

UI Framework: [Chakra UI](https://chakra-ui.com/) - An easy to use and powerful UI framework that allows for css-in-js
Helper functions: [lodash](https://lodash.com/) - General functional helper tools that can help us do things like empty checks on objects, deep clones, etc
Date Helpers: [date-fns](https://date-fns.org/) - An advanced library to take the pain out of regular `Date` objects
Icon pack: [react-icons](https://react-icons.github.io/react-icons/) - An icon pack recommended by Chakra which allows for many, many icons including font-awesome
Markdown Plugin: [react-markdown](https://github.com/remarkjs/react-markdown) - Processes `.md` files to allow us to create blog posts and render them all in a consistent way in the frontend. (For challenges)
Bundler: [Vite](https://vitejs.dev/) - Not sure it's possible to use this bundler with NextJS but if so, Vite offers an amazing hot reload and development experience plus a no-hassle build for production.
Database: [PostgresQL](https://www.postgresql.org/) and [GraphQL](https://graphql.org/) - Postgres is industry proven and easy to use, GraphQL provides a great interface for database queries.

**Comment by codeTrackLift** [comment]
Closing this issue for now as PR #3 has been merged.
