### ISSUE TITLE
Fix: Hero image resolution

### ISSUE THREAD

**Issue by codeTrackLift** [mitxpro-dev/learnjs#22]
- The hero `image` looks pixelated at desktop resolution, see screenshot below.
- Find and propose a solution.
- Dev notes:
  - It looks like the hero image is from the Unsplash `api`
  - Image `width` looks to be accessible as a query param, `1440px` might be nice?
  - Link to [Unsplash documentation](https://unsplash.com/documentation#supported-parameters) on query params
  - Bonus: extract the `url` as a constant that is declared below the imports

<details>
<summary>Click here to see screenshot</summary>
  
![Screenshot 2023-07-04 at 9 54 07 AM](https://github.com/mitxpro-dev/learnjs/assets/96446064/dd480e20-6485-410c-aacb-222b30a1888f)

</details>

**Comment by codeTrackLift** [comment]
CC: @drewpate if you have time, this might be a nice follow-up to your [PR# 13](https://github.com/mitxpro-dev/learnjs/pull/13), but all good either way.

**Comment by drewpate** [comment]
@codeTrackLift absolutely! I'll see what I can do after the holiday.

**Comment by HudsonGraeme** [comment]
@drewpate Thanks!!

**Comment by drewpate** [comment]
@codeTrackLift @HudsonGraeme I made some changes based on the previous input. Image resolution was looking better on my end. I think there's a merge that was not supposed to happen. I'm still working from my own fork for now.

**Comment by codeTrackLift** [comment]
Sorry @drewpate, that was my bad.  I merged PR #13 for you.
